name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: |
          npm install

      - name: Install Snapcraft
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo snap install snapcraft --classic
          echo "$SNAP_TOKEN" | snapcraft login --with -
        env:
          SNAP_TOKEN: ${{ secrets.snapcraft_token }}

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}}

        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always
